name: C/C++ CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjsoncpp-dev uuid-dev zlib1g-dev openssl libssl-dev
    - name: Install Drogon
      run: |
        git clone https://github.com/drogonframework/drogon
        cd drogon
        git submodule update --init --recursive

        mkdir build && cd build
        cmake ..
        make && sudo make install
    - name: Build project
      run: |
        mkdir build && cd build
        cmake ..
        make
    - name: Test run
      run: |
        cd build
        ./MyDrogonAPI &
        sleep 10
        kill $!
